CREATE TABLE account
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       VARCHAR(255),
    nature            VARCHAR(20)  NOT NULL,
    parent_account_id BIGINT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT fk_account_parent FOREIGN KEY (parent_account_id) REFERENCES account (id) ON DELETE CASCADE,

    CONSTRAINT chk_account_nature CHECK (nature IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'))
);

CREATE INDEX idx_account_user ON account (user_id);
CREATE INDEX idx_account_parent ON account (parent_account_id);
CREATE UNIQUE INDEX uk_account_name_user ON account (user_id, name, nature);

COMMENT ON COLUMN account.nature IS 'Naturezas esperadas: ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE';