CREATE TABLE journal_entry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    date        DATE         NOT NULL,
    description VARCHAR(255) NOT NULL,
    status      VARCHAR(50)  NOT NULL DEFAULT 'COMPLETED',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_journal_entry_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX idx_journal_entry_user_date ON journal_entry (user_id, date);

COMMENT ON COLUMN journal_entry.status IS 'Status esperadas: COMPLETED, PENDING, CANCELLED';

--------------------------- X-X ---------------------------

CREATE TABLE ledger_entry
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT         NOT NULL,
    account_id       BIGINT         NOT NULL,
    entry_type       VARCHAR(10)    NOT NULL,
    amount           NUMERIC(15, 2) NOT NULL,

    CONSTRAINT fk_ledger_entry_journal FOREIGN KEY (journal_entry_id) REFERENCES journal_entry (id) ON DELETE CASCADE,
    CONSTRAINT fk_ledger_entry_account FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT,

    CONSTRAINT chk_ledger_entry_amount CHECK (amount > 0),
    CONSTRAINT chk_ledger_entry_type CHECK (entry_type IN ('DEBIT', 'CREDIT'))
);

CREATE INDEX idx_ledger_entry_journal ON ledger_entry (journal_entry_id);
CREATE INDEX idx_ledger_entry_account ON ledger_entry (account_id);