CREATE TABLE journal_entry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL,
    date        DATE           NOT NULL,
    description VARCHAR(255)   NOT NULL,
    status      VARCHAR(50)    NOT NULL DEFAULT 'COMPLETED',
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_journal_entry_user    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT chk_journal_entry_status CHECK (status IN ('COMPLETED', 'PENDING', 'CANCELLED'))
);

CREATE INDEX idx_journal_entry_user_date ON journal_entry (user_id, date DESC);

COMMENT ON TABLE  journal_entry            IS 'Cabeçalho do lançamento contábil (partidas dobradas)';
COMMENT ON COLUMN journal_entry.date       IS 'Data contábil do lançamento (pode diferir da data de registro)';
COMMENT ON COLUMN journal_entry.status     IS 'COMPLETED | PENDING | CANCELLED';

CREATE TABLE ledger_entry
(
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    occurred_at      TIMESTAMPTZ    NOT NULL,
    journal_entry_id BIGINT         NOT NULL,
    account_id       BIGINT         NOT NULL,
    entry_type       VARCHAR(10)    NOT NULL,
    amount           NUMERIC(15, 2) NOT NULL,

    PRIMARY KEY (id, occurred_at),

    CONSTRAINT fk_ledger_entry_journal  FOREIGN KEY (journal_entry_id) REFERENCES journal_entry (id) ON DELETE CASCADE,
    CONSTRAINT fk_ledger_entry_account  FOREIGN KEY (account_id)       REFERENCES account (id)        ON DELETE RESTRICT,

    CONSTRAINT chk_ledger_entry_amount  CHECK (amount > 0),
    CONSTRAINT chk_ledger_entry_type    CHECK (entry_type IN ('DEBIT', 'CREDIT'))
);

SELECT create_hypertable(
    'ledger_entry',
    'occurred_at',
    chunk_time_interval => INTERVAL '1 month',
    if_not_exists       => TRUE
);

CREATE INDEX idx_ledger_entry_account_time  ON ledger_entry (account_id,       occurred_at DESC);
CREATE INDEX idx_ledger_entry_journal_time  ON ledger_entry (journal_entry_id, occurred_at DESC);

ALTER TABLE ledger_entry
    SET (
        timescaledb.compress,
        timescaledb.compress_segmentby = 'account_id, entry_type',
        timescaledb.compress_orderby   = 'occurred_at DESC'
    );

SELECT add_compression_policy(
    'ledger_entry',
    INTERVAL '6 months',
    if_not_exists => TRUE
);

COMMENT ON TABLE  ledger_entry                 IS 'Linhas do lançamento contábil — hypertable TimescaleDB, append-only';
COMMENT ON COLUMN ledger_entry.occurred_at     IS 'Timestamp do registro (coluna de particionamento da hypertable)';
COMMENT ON COLUMN ledger_entry.entry_type      IS 'DEBIT | CREDIT';
COMMENT ON COLUMN ledger_entry.amount          IS 'Sempre positivo — o entry_type define a direção';
