CREATE TABLE user_telephone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    area_code VARCHAR(5) NOT NULL,
    telephone VARCHAR(15) NOT NULL,
    type VARCHAR(20) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_user_telephone_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_telephone_user_id ON user_telephone (user_id);
CREATE UNIQUE INDEX uk_user_telephone_primary_by_type ON user_telephone (user_id, type) WHERE is_primary = TRUE;
