CREATE TABLE copom_meeting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_date DATE NOT NULL,
    meeting_number INT,
    description VARCHAR(255),
    previous_selic_target NUMERIC(10, 2),
    selic_target NUMERIC(10, 2),
    minutes_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN copom_meeting.meeting_date IS 'Data do segundo dia da reunião (decisão)';
COMMENT ON COLUMN copom_meeting.previous_selic_target IS 'Meta vigente antes da reunião';
COMMENT ON COLUMN copom_meeting.selic_target IS 'Nova meta definida';

CREATE INDEX idx_copom_meeting_date ON copom_meeting (meeting_date);
