CREATE TABLE holiday (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_holiday_date_country UNIQUE (date, country_code)
);

CREATE INDEX idx_holiday_name ON holiday (name);
CREATE INDEX idx_holiday_date ON holiday (date);
