CREATE TABLE source_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    storage_path VARCHAR(500) NOT NULL,
    domain VARCHAR(100) NOT NULL,
    content_type VARCHAR(100),
    user_id BIGINT,
    file_size BIGINT,
    checksum VARCHAR(64),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_source_file_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX idx_source_file_user ON source_file (user_id);
CREATE INDEX idx_source_file_checksum ON source_file (checksum);
CREATE INDEX idx_source_file_status ON source_file (status);

CREATE TABLE source_file_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_id BIGINT NOT NULL,
    error_message TEXT NOT NULL,
    location_reference VARCHAR(255),
    raw_data TEXT,
    error_details JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_error_source_file FOREIGN KEY (source_file_id) REFERENCES source_file (id) ON DELETE CASCADE
);

CREATE INDEX idx_error_source_file ON source_file_error (source_file_id);
