CREATE TABLE user_email (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type ENUM('PERSONAL', 'PROFESSIONAL', 'COMMERCIAL') NOT NULL DEFAULT 'PERSONAL',
  email VARCHAR(100) NOT NULL,

  is_primary BOOLEAN   NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status ENUM('ACTIVE', 'INACTIVE', 'UNVERIFIED', 'OUTDATED', 'WRONG_PERSON', 'INVALID') NOT NULL DEFAULT 'ACTIVE',

  CONSTRAINT fk_user_email_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  INDEX idx_user_email_user_id (user_id),
  INDEX idx_user_email_user_primary (user_id, is_primary)
);